model_list:
  - model_name: bedrock-claude-3-5-sonnet
    litellm_params:
      model: 'bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0'
      aws_region_name: ap-southeast-1
  - model_name: bedrock-claude-3-5-sonnet-v2
    litellm_params:
      model: 'bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0'
      aws_region_name: ap-southeast-1
  - model_name: bedrock-claude-3-7-sonnet
    litellm_params:
      model: 'bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0'
      aws_region_name: us-east-1
  - model_name: bedrock-claude-3-sonnet
    litellm_params:
      model: 'bedrock/anthropic.claude-3-sonnet-20240229-v1:0'
  - model_name: bedrock-llama3-8b-instruct-v1
    litellm_params:
      model: 'bedrock/meta.llama3-8b-instruct-v1:0'
  - model_name: bedrock-mixtral-8x7b-instruct-v0
    litellm_params:
      model: 'bedrock/mistral.mixtral-8x7b-instruct-v0:1'
router_settings:
  redis_host: litellm-redis.production.singapore
  redis_password: ''
  redis_port: 6379
general_settings:
  master_key: sk-1234      
  alerting: ["slack"]     
  proxy_batch_write_at: 60 # Batch write spend updates every 60s
  database_connection_pool_limit: 10 # limit the number

  # OPTIONAL Best Practices
  disable_spend_logs: True # turn off writing each transaction to the db. We recommend doing this is you don't need to see Usage on the LiteLLM UI and are tracking metrics via Prometheus
  disable_error_logs: True # turn off writing LLM Exceptions to DB
  allow_requests_on_db_unavailable: True 

litellm_settings:
  request_timeout: 600    # raise Timeout error if call takes longer than 600 seconds. Default value is 6000seconds if not set
  set_verbose: False      # Switch off Debug Logging, ensure your logs do not have any debugging on
  json_logs: true    
